package com.example.sudoku;

import android.os.Parcel;
import android.os.Parcelable;
import androidx.annotation.NonNull;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import java.util.Stack;

/**
 * Represents the state and logic of a Sudoku board. This class manages puzzle generation, move validation, cell states,
 * and the history of moves for the undo functionality.
 */
public class SudokuBoard implements Parcelable {

    private static final int MAX_PUZZLE_GENERATION_ATTEMPTS = 8;

    /**
     * Enum for Sudoku difficulty levels. It determines how many numbers are removed from a fully solved grid.
     */
    public enum Difficulty {
        EASY(35), MEDIUM(45), HARD(55);

        public final int cellsToRemove;

        Difficulty(int cellsToRemove) {
            this.cellsToRemove = cellsToRemove;
        }
    }

    /**
     * A private static nested class to represent a single move made by the user. Used for the move history stack. Making it
     * static means it doesn't hold an implicit reference to the outer SudokuBoard instance.
     */
    public static class MoveRecord {
        final int row;
        final int col;
        final int oldValue;
        final int newValue;
        final int scoreChange;
        final boolean wasError;

        MoveRecord(int row, int col, int oldValue, int newValue, int scoreChange, boolean wasError) {
            this.row = row;
            this.col = col;
            this.oldValue = oldValue;
            this.newValue = newValue;
            this.scoreChange = scoreChange;
            this.wasError = wasError;
        }

        public int getScoreChange() {
            return scoreChange;
        }

        public boolean wasError() {
            return wasError;
        }
    }

    private Difficulty currentDifficulty;
    // The complete solution grid, generated at the start.
    // Used to check the correctness of user moves.
    private int[][] solutionBoard;

    // The game grid visible to the user, composed of SudokuCell objects.
    private SudokuCell[][] board;

    // Stack to track moves for the undo feature.
    private final Stack<MoveRecord> movesHistory;

    private final Random random = new Random();

    /**
     * Default constructor. Initializes the board structures. The puzzle itself must be generated by calling
     * generateNewPuzzle().
     */
    public SudokuBoard() {
        this.currentDifficulty = Difficulty.MEDIUM;
        // In Java, we must explicitly initialize the arrays.
        this.solutionBoard = new int[9][9];
        this.board = new SudokuCell[9][9];
        // It's crucial to also initialize each SudokuCell object in the grid.
        for (int r = 0; r < 9; r++) {
            for (int c = 0; c < 9; c++) {
                this.board[r][c] = new SudokuCell();
            }
        }
        this.movesHistory = new Stack<>();
    }

    /**
     * Generates a new Sudoku puzzle with the specified difficulty.
     *
     * @param difficulty The difficulty level for the new puzzle.
     */
    public void generateNewPuzzle(Difficulty difficulty) throws InterruptedException {
        this.currentDifficulty = difficulty;
        this.movesHistory.clear();
        for (int attempt = 0; attempt < MAX_PUZZLE_GENERATION_ATTEMPTS; attempt++) {
            if (Thread.currentThread().isInterrupted()) {
                throw new InterruptedException("Puzzle generation was cancelled.");
            }

            clearLogicalBoard();

            // This will fill the solutionBoard with a valid, complete Sudoku grid.
            fillBoardRecursive(0, 0);

            // Copy the solution to the user-facing board.
            for (int r = 0; r < 9; r++) {
                for (int c = 0; c < 9; c++) {
                    board[r][c] = new SudokuCell(solutionBoard[r][c], false, true, null);
                }
            }

            if (removeNumbersForPuzzle(difficulty.cellsToRemove)) {
                // Mark the remaining numbers as fixed.
                for (int r = 0; r < 9; r++) {
                    for (int c = 0; c < 9; c++) {
                        if (board[r][c].getValue() != 0) {
                            board[r][c].setFixed(true);
                        }
                    }
                }
                return;
            }
        }

        throw new IllegalStateException("Unable to generate a unique puzzle after " + MAX_PUZZLE_GENERATION_ATTEMPTS
                + " attempts.");
    }

    /**
     * Retrieves the cell at the specified row and column.
     *
     * @param row The row (0-8).
     * @param col The column (0-8).
     * @return The SudokuCell at that position, or null if coordinates are out of bounds.
     */
    public SudokuCell getCell(int row, int col) {
        if (isValidCoordinate(row, col)) {
            return board[row][col];
        }
        return null;
    }

    /**
     * Sets the value of a cell and records the move. The correctness of the input value is checked against the complete
     * solution.
     *
     * @param row         The row (0-8).
     * @param col         The column (0-8).
     * @param value       The value (1-9) to insert. If 0, the cell is cleared.
     * @param scoreChange The change in score associated with this move.
     * @param wasError    True if the move was an error, false otherwise.
     */
    public void setCellValue(int row, int col, int value, int scoreChange, boolean wasError) {
        if (!isValidCoordinate(row, col) || board[row][col].isFixed() || value < 0 || value > 9) {
            return;
        }

        SudokuCell cell = board[row][col];
        int oldValue = cell.getValue();

        if (oldValue == value)
            return;

        cell.setValue(value);
        if (value != 0) {
            cell.setCorrect(value == solutionBoard[row][col]);
        } else {
            cell.setCorrect(true); // An empty cell is not considered "incorrect".
        }

        movesHistory.push(new MoveRecord(row, col, oldValue, value, scoreChange, wasError));
    }

    /**
     * Undoes the last move made. Restores the previous value of the modified cell.
     *
     * @return The `MoveRecord` of the undone move, or `null` if there are no moves to undo.
     */
    public MoveRecord undoMove() {
        if (!movesHistory.isEmpty()) {
            MoveRecord lastMove = movesHistory.pop();
            SudokuCell cell = board[lastMove.row][lastMove.col];
            cell.setValue(lastMove.oldValue);
            if (cell.getValue() != 0) {
                cell.setCorrect(cell.getValue() == solutionBoard[lastMove.row][lastMove.col]);
            } else {
                cell.setCorrect(true);
            }
            return lastMove;
        }
        return null;
    }

    /**
     * Checks if the entire board is filled with numbers.
     *
     * @return `true` if no cell has a value of 0, `false` otherwise.
     */
    public boolean isBoardFull() {
        for (int r = 0; r < 9; r++) {
            for (int c = 0; c < 9; c++) {
                if (board[r][c].getValue() == 0) {
                    return false;
                }
            }
        }
        return true;
    }

    /**
     * Counts the number of incorrect user-entered values on the board.
     *
     * @return The total count of errors.
     */
    public int countUserErrors() {
        int errors = 0;
        for (int r = 0; r < 9; r++) {
            for (int c = 0; c < 9; c++) {
                SudokuCell cell = board[r][c];
                if (!cell.isFixed() && cell.getValue() != 0 && !cell.isCorrect()) {
                    errors++;
                }
            }
        }
        return errors;
    }

    /**
     * Checks if the current user-entered numbers are correct according to the solution. It only validates non-fixed cells
     * that have a value.
     *
     * @return {@code true} if all user-entered numbers match the solution, {@code false} otherwise.
     */
    public boolean areAllUserCellsCorrect() {
        for (int r = 0; r < 9; r++) {
            for (int c = 0; c < 9; c++) {
                SudokuCell cell = board[r][c];
                // Check only user-entered (non-fixed) cells with a value.
                if (!cell.isFixed() && cell.getValue() != 0) {
                    if (cell.getValue() != solutionBoard[r][c]) {
                        return false;
                    }
                }
            }
        }
        return true;
    }

    /**
     * Checks if a given value for a cell is correct according to the solution.
     *
     * @param row The row of the cell.
     * @param col The column of the cell.
     * @param value The value to check.
     * @return {@code true} if the value is correct for the cell, {@code false} otherwise.
     */
    public boolean isMoveCorrect(int row, int col, int value) {
        if (isValidCoordinate(row, col)) {
            return solutionBoard[row][col] == value;
        }
        return false;
    }

    /**
     * Checks if the current state of the board is valid according to basic Sudoku rules (no duplicates in any row, column,
     * or 3x3 subgrid). This check does not use the solution, it only validates the current numbers on the board against
     * each other.
     *
     * @return {@code true} if the current board is valid by the rules, {@code false} otherwise.
     */
    public boolean isCurrentBoardStateValidAccordingToRules() {
        // Create a temporary int array representing the current board values.
        int[][] currentValues = new int[9][9];
        for (int r = 0; r < 9; r++) {
            for (int c = 0; c < 9; c++) {
                currentValues[r][c] = board[r][c].getValue();
            }
        }

        for (int r = 0; r < 9; r++) {
            for (int c = 0; c < 9; c++) {
                int num = currentValues[r][c];
                if (num != 0) {
                    // Temporarily remove the number to check if placing it is "safe"
                    // against the rest of the numbers on the board.
                    currentValues[r][c] = 0;
                    boolean safe = isSafe(currentValues, r, c, num);
                    // Put the number back.
                    currentValues[r][c] = num;
                    if (!safe) {
                        return false; // Found a rule violation.
                    }
                }
            }
        }
        return true; // No rule violations found.
    }

    public Difficulty getCurrentDifficulty() {
        return currentDifficulty;
    }

    /* ----- Private Helper Methods ----- */

    /**
     * Resets the logical boards to an empty state.
     */
    private void clearLogicalBoard() {
        solutionBoard = new int[9][9]; // Re-initialize array (all values default to 0)
        board = new SudokuCell[9][9];
        for (int r = 0; r < 9; r++) {
            for (int c = 0; c < 9; c++) {
                board[r][c] = new SudokuCell();
            }
        }
    }

    /**
     * Recursive backtracking algorithm to fill the solutionBoard.
     *
     * @param row The current row to process.
     * @param col The current column to process.
     * @return `true` if the board was successfully filled, `false` otherwise.
     */
    private boolean fillBoardRecursive(int row, int col) {
        int currentRow = row;
        int currentCol = col;

        if (currentCol == 9) {
            currentRow++;
            currentCol = 0;
            if (currentRow == 9) {
                return true; // Board is successfully filled
            }
        }

        // Create a shuffled list of numbers to try, for randomness.
        List<Integer> numbers = new ArrayList<>();
        for (int i = 1; i <= 9; i++) {
            numbers.add(i);
        }
        Collections.shuffle(numbers, random);

        for (int num : numbers) {
            if (isSafe(solutionBoard, currentRow, currentCol, num)) {
                solutionBoard[currentRow][currentCol] = num;
                if (fillBoardRecursive(currentRow, currentCol + 1)) {
                    return true;
                }
                // Backtrack
                solutionBoard[currentRow][currentCol] = 0;
            }
        }
        return false;
    }

    /**
     * Removes a specified number of cells from the board to create the puzzle, ensuring that the puzzle still has a unique
     * solution.
     *
     * @param cellsToRemove The number of cells to make empty.
     */
    private boolean removeNumbersForPuzzle(int cellsToRemove) throws InterruptedException {
        List<Integer> positions = new ArrayList<>(81);
        for (int index = 0; index < 81; index++) {
            positions.add(index);
        }
        Collections.shuffle(positions, random);

        int removedCount = 0;
        for (int position : positions) {
            if (Thread.currentThread().isInterrupted()) {
                throw new InterruptedException("Puzzle generation was cancelled.");
            }

            int row = position / 9;
            int col = position % 9;
            if (board[row][col].getValue() == 0) {
                continue;
            }

            int previousValue = board[row][col].getValue();
            board[row][col].setValue(0);

            // Removing more clues can only make uniqueness harder to preserve, so a
            // clue that already fails this check would not become removable later.
            if (countUniqueSolutions(copyBoardValues(), 0) == 1) {
                removedCount++;
                if (removedCount == cellsToRemove) {
                    return true;
                }
            } else {
                board[row][col].setValue(previousValue);
            }
        }

        return false;
    }

    private int[][] copyBoardValues() {
        int[][] copy = new int[9][9];
        for (int row = 0; row < 9; row++) {
            for (int col = 0; col < 9; col++) {
                copy[row][col] = board[row][col].getValue();
            }
        }
        return copy;
    }

    /**
     * Recursively counts the number of possible solutions for a given grid state. Stops and returns immediately if more
     * than one solution is found.
     *
     * @param currentGrid The current state of the board as a 2D int array.
     * @param count The current count of solutions found.
     * @return The number of solutions (0, 1, or 2 if more than one).
     */
    private int countUniqueSolutions(int[][] currentGrid, int count) throws InterruptedException {
        if (Thread.currentThread().isInterrupted()) {
            throw new InterruptedException();
        }
        int solutionCount = count;
        for (int r = 0; r < 9; r++) {
            for (int c = 0; c < 9; c++) {
                if (currentGrid[r][c] == 0) {
                    for (int num = 1; num <= 9; num++) {
                        if (isSafe(currentGrid, r, c, num)) {
                            currentGrid[r][c] = num;
                            solutionCount = countUniqueSolutions(currentGrid, solutionCount);
                            // Optimization: if we already found more than 1 solution, stop searching.
                            if (solutionCount > 1)
                                return solutionCount;
                            // Backtrack
                            currentGrid[r][c] = 0;
                        }
                    }
                    return solutionCount;
                }
            }
        }
        return solutionCount + 1; // A full traversal means one complete solution was found.
    }

    /**
     * Checks if placing a number in a given cell is valid according to Sudoku rules.
     *
     * @param targetBoard The board to check against.
     * @param row The row of the cell.
     * @param col The column of the cell.
     * @param num The number to check.
     * @return `true` if the placement is safe, `false` otherwise.
     */
    private boolean isSafe(int[][] targetBoard, int row, int col, int num) {
        // Check row
        for (int cIdx = 0; cIdx < 9; cIdx++) {
            if (targetBoard[row][cIdx] == num)
                return false;
        }
        // Check column
        for (int rIdx = 0; rIdx < 9; rIdx++) {
            if (targetBoard[rIdx][col] == num)
                return false;
        }
        // Check 3x3 subgrid
        int startRow = row - row % 3;
        int startCol = col - col % 3;
        for (int rOffset = 0; rOffset < 3; rOffset++) {
            for (int cOffset = 0; cOffset < 3; cOffset++) {
                if (targetBoard[startRow + rOffset][startCol + cOffset] == num)
                    return false;
            }
        }
        return true;
    }

    /**
     * Checks if the given coordinates are within the 9x9 grid.
     */
    private boolean isValidCoordinate(int row, int col) {
        return row >= 0 && row < 9 && col >= 0 && col < 9;
    }

    /* ----- Parcelable Implementation ----- */

    protected SudokuBoard(Parcel in) {
        currentDifficulty = Difficulty.valueOf(in.readString());
        solutionBoard = new int[9][9];
        for (int i = 0; i < 9; i++) {
            in.readIntArray(solutionBoard[i]);
        }

        board = new SudokuCell[9][9];
        for (int i = 0; i < 9; i++) {
            // Reading an array of Parcelable objects.
            SudokuCell[] row = in.createTypedArray(SudokuCell.CREATOR);
            if (row != null) {
                board[i] = row;
            }
        }

        movesHistory = new Stack<>();
        int historySize = in.readInt();
        for (int i = 0; i < historySize; i++) {
            movesHistory.push(new MoveRecord(in.readInt(), in.readInt(), in.readInt(), in.readInt(), in.readInt(),
                    in.readByte() != 0));
        }
    }

    public static final Creator<SudokuBoard> CREATOR = new Creator<>() {
        @Override
        public SudokuBoard createFromParcel(Parcel in) {
            return new SudokuBoard(in);
        }

        @Override
        public SudokuBoard[] newArray(int size) {
            return new SudokuBoard[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(@NonNull Parcel dest, int flags) {
        dest.writeString(currentDifficulty.name());

        for (int i = 0; i < 9; i++) {
            dest.writeIntArray(solutionBoard[i]);
        }

        for (int i = 0; i < 9; i++) {
            dest.writeTypedArray(board[i], flags);
        }

        dest.writeInt(movesHistory.size());
        for (MoveRecord move : movesHistory) {
            dest.writeInt(move.row);
            dest.writeInt(move.col);
            dest.writeInt(move.oldValue);
            dest.writeInt(move.newValue);
            dest.writeInt(move.scoreChange);
            dest.writeByte((byte) (move.wasError ? 1 : 0));
        }
    }
}
